# Generated by Django 2.2.3 on 2019-11-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstSem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=20, null=True)),
                ('roll_no', models.CharField(max_length=7, unique=True)),
                ('webTech', models.IntegerField(blank=True, null=True)),
                ('compiler', models.IntegerField(blank=True, null=True)),
                ('rts', models.IntegerField(blank=True, null=True)),
                ('software', models.IntegerField(blank=True, null=True)),
                ('dot_net', models.IntegerField(blank=True, null=True)),
                ('e_commerce', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecondSem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=20, null=True)),
                ('roll_no', models.CharField(max_length=5, unique=True)),
                ('webTech', models.IntegerField(blank=True, null=True)),
                ('compiler', models.IntegerField(blank=True, null=True)),
                ('rts', models.IntegerField(blank=True, null=True)),
                ('software', models.IntegerField(blank=True, null=True)),
                ('dot_net', models.IntegerField(blank=True, null=True)),
                ('e_commerce', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdSem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=19, null=True)),
                ('roll_no', models.CharField(max_length=2, unique=True)),
                ('webTech', models.IntegerField(blank=True, null=True)),
                ('compiler', models.IntegerField(blank=True, null=True)),
                ('rts', models.IntegerField(blank=True, null=True)),
                ('software', models.IntegerField(blank=True, null=True)),
                ('dot_net', models.IntegerField(blank=True, null=True)),
                ('e_commerce', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sixthsem',
            name='user',
        ),
        migrations.AlterField(
            model_name='sixthsem',
            name='compiler',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sixthsem',
            name='dot_net',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sixthsem',
            name='e_commerce',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sixthsem',
            name='rts',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sixthsem',
            name='software',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sixthsem',
            name='webTech',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
