# Generated by Django 2.2.3 on 2019-11-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marks', '0004_auto_20191123_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstsem',
            old_name='compiler',
            new_name='C_programming',
        ),
        migrations.RenameField(
            model_name='firstsem',
            old_name='dot_net',
            new_name='Digital',
        ),
        migrations.RenameField(
            model_name='firstsem',
            old_name='e_commerce',
            new_name='F_it',
        ),
        migrations.RenameField(
            model_name='firstsem',
            old_name='rts',
            new_name='Physics',
        ),
        migrations.RenameField(
            model_name='firstsem',
            old_name='software',
            new_name='math',
        ),
        migrations.RenameField(
            model_name='secondsem',
            old_name='compiler',
            new_name='discrete',
        ),
        migrations.RenameField(
            model_name='secondsem',
            old_name='dot_net',
            new_name='math_ii',
        ),
        migrations.RenameField(
            model_name='secondsem',
            old_name='e_commerce',
            new_name='micro',
        ),
        migrations.RenameField(
            model_name='secondsem',
            old_name='rts',
            new_name='oop',
        ),
        migrations.RenameField(
            model_name='secondsem',
            old_name='software',
            new_name='stat_i',
        ),
        migrations.RenameField(
            model_name='thirdsem',
            old_name='compiler',
            new_name='ca',
        ),
        migrations.RenameField(
            model_name='thirdsem',
            old_name='dot_net',
            new_name='cg',
        ),
        migrations.RenameField(
            model_name='thirdsem',
            old_name='e_commerce',
            new_name='dsa',
        ),
        migrations.RenameField(
            model_name='thirdsem',
            old_name='rts',
            new_name='nm',
        ),
        migrations.RenameField(
            model_name='thirdsem',
            old_name='software',
            new_name='stat_ii',
        ),
        migrations.RemoveField(
            model_name='firstsem',
            name='webTech',
        ),
        migrations.RemoveField(
            model_name='secondsem',
            name='webTech',
        ),
        migrations.RemoveField(
            model_name='thirdsem',
            name='webTech',
        ),
    ]
