# Generated by Django 2.2.3 on 2019-11-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marks', '0005_auto_20191124_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstsem',
            old_name='roll_no',
            new_name='roll',
        ),
    ]
