# Generated by Django 2.2.3 on 2019-12-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='file',
        ),
        migrations.RemoveField(
            model_name='news',
            name='user',
        ),
        migrations.AddField(
            model_name='news',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
