# Generated by Django 2.2.3 on 2019-12-14 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_auto_20191214_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='profile',
            new_name='file',
        ),
    ]
